const products = [
  {
    _id: "1",
    name: "Airpods Wireless Bluetooth Headphones",
    image: "/images/airpods.jpg",
    description:
      "Bluetooth technology lets you connect it with compatible devices wirelessly. High-quality AAC audio offers an immersive listening experience. Built-in microphone allows you to take calls while working.",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "Smartphone X",
    image: "/images/phone.jpg",
    description:
      "Powerful smartphone with advanced features. High-resolution display, dual-camera setup, and long-lasting battery life.",
    brand: "XYZ",
    category: "Electronics",
    price: 499.99,
    countInStock: 5,
    rating: 4.2,
    numReviews: 8,
  },
  {
    _id: "3",
    name: "Laptop Pro",
    image: "/images/alexa.jpg",
    description:
      "High-performance laptop for work and entertainment. Stunning display, powerful processor, and long battery life.",
    brand: "TechGear",
    category: "Computers",
    price: 1299.99,
    countInStock: 3,
    rating: 4.7,
    numReviews: 15,
  },
  {
    _id: "4",
    name: "4K Ultra HD TV",
    image: "/images/camera.jpg",
    description:
      "Immerse yourself in stunning 4K visuals. Smart TV features for streaming and entertainment.",
    brand: "Visionary",
    category: "Televisions",
    price: 899.99,
    countInStock: 7,
    rating: 4.8,
    numReviews: 10,
  },
  {
    _id: "5",
    name: "Gaming Console X",
    image: "/images/playstation.jpg",
    description:
      "Next-gen gaming console for immersive gaming experiences. High-fidelity graphics and responsive controls.",
    brand: "GamerTech",
    category: "Gaming",
    price: 599.99,
    countInStock: 2,
    rating: 4.6,
    numReviews: 18,
  },
  {
    _id: "6",
    name: "Smartwatch Series 5",
    image: "/images/phone.jpg",
    description:
      "Stay connected with notifications, fitness tracking, and heart rate monitoring. Sleek design with customizable watch faces.",
    brand: "TechCo",
    category: "Wearable Technology",
    price: 199.99,
    countInStock: 15,
    rating: 4.7,
    numReviews: 20,
  },
  {
    _id: "7",
    name: "Digital Camera DSLR",
    image: "/images/camera.jpg",
    description:
      "Capture stunning photos and videos with professional-grade features. Interchangeable lenses and advanced shooting modes.",
    brand: "PhotoPro",
    category: "Cameras",
    price: 1299.99,
    countInStock: 4,
    rating: 4.9,
    numReviews: 22,
  },
  {
    _id: "8",
    name: "Wireless Keyboard and Mouse Set",
    image: "/images/mouse.jpg",
    description:
      "Convenient set for seamless computer usage. Wireless connectivity and ergonomic design for comfort.",
    brand: "TechEase",
    category: "Computer Accessories",
    price: 49.99,
    countInStock: 20,
    rating: 4.8,
    numReviews: 15,
  },
  {
    _id: "9",
    name: "Bluetooth Speaker System",
    image: "/images/airpods.jpg",
    description:
      "Immersive audio experience with powerful bass and clear treble. Bluetooth connectivity for wireless music streaming.",
    brand: "SoundTech",
    category: "Audio",
    price: 149.99,
    countInStock: 8,
    rating: 4.4,
    numReviews: 14,
  },
  // Add more products as needed
];
export default products;
